---
output: 
  html_document: 
    #theme: null
    #highlight: null
    mathjax: null
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(dirname(inputFile), '/www/Welcome.html')) })

---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
library(OCSRiskCalculator)
```

### **Welcome to this Web Application! Please review the below instructions prior to entering the application**

This Web app may aid individuals who are using or have previously used oral corticosteroids to estimate their risk of various adverse health outcomes associated with oral corticosteroid use.

All the calculations in this application are based on a 2018 scientific study in the Journal of Allergy and Clinical Immunology [(Click here to access the publication page)](http://dx.doi.org/10.1016/j.jaci.2017.04.009){target="_blank"}. 

### Things to remember when using this Web Application: 

* **This web app must be used in consultation with your care provider**

* This web app calculates the **Relative Risk**.
  + A relative risk of 1.5 for someone who is using oral   corticosteroids means a relative increase in risk of 50% compared with someone who is not taking oral corticosteroids. 
  + For example, for someone with a baseline risk of 2% for an outcome, a 50% relative risk increase means the risk is increased to 3%  (that is, an extra 1%). 
  + However, for someone with baseline risk of 10%, the same relative increase means their risk will become 15% that is, an extra 5% in risk).

* Your **baseline risk** is affected by many factors, such as your age and gender. The baseline risk for an outcome should generally be estimated in consultation with your healthcare provider and should not be derived from this web application.
  + The absolute value of change in risk is dependent on the **baseline risk**. 
  

```{=html}
<p><span style="color:Tomato">Warning: This tool SHOULD NOT BE USED to replace a diagnostic or treatment decision made by a physician. </span>
               <br></p>
               <p>For a detailed description of the tool, please refer to the About page on top</a>.</p>
```

### Terms of Use
```{R echo=FALSE, warning=FALSE}
library(OCSRiskCalculator)
library(htmltools)
pre(OCSRiskCalculator::terms_of_use())
```

### Before you start
Before using this app, please click on the check box below to indicate that you consent to use this tool and understand the risk of using the tool without proper consultation with an expert. 


